from .croniclexception import CroniclException

class ValidationError(CroniclException): pass
